CREATE DATABASE DBMS
CONTAINMENT=NONE
ON PRIMARY (CANDIDATE_NAME=N'dbms_main', FILENAME=N'/var/opt/mssql/data/dbms_primary/dbms_primary.mdf', SIZE=8192KB, FILEGROWTH=65535KB)
LOG ON (CANDIDATE_NAME=N'dbms_log', FILENAME=N'/var/opt/mssql/data/dbms_log/dbms_log.ldf', SIZE=8192KB, FILEGROWTH=65535KB)
GO

ALTER DATABASE DBMS ADD FILEGROUP FG1
ALTER DATABASE DBMS ADD FILE (CANDIDATE_NAME=N'FG1_F1', FILENAME=N'/var/opt/mssql/data/dbms_data/disk1/fg1_f1.ndf', SIZE=8192KB , FILEGROWTH=65536KB) TO FILEGROUP FG1
ALTER DATABASE DBMS ADD FILE (CANDIDATE_NAME=N'FG1_F2', FILENAME=N'/var/opt/mssql/data/dbms_data/disk2/fg1_f2.ndf', SIZE=8192KB , FILEGROWTH=65536KB) TO FILEGROUP FG1
ALTER DATABASE DBMS ADD FILEGROUP FG2
ALTER DATABASE DBMS ADD FILE (CANDIDATE_NAME=N'FG2_F1', FILENAME=N'/var/opt/mssql/data/dbms_data/disk1/fg2_f1.ndf', SIZE=8192KB , FILEGROWTH=65536KB) TO FILEGROUP FG2
ALTER DATABASE DBMS ADD FILE (CANDIDATE_NAME=N'FG2_F2', FILENAME=N'/var/opt/mssql/data/dbms_data/disk2/fg2_f2.ndf', SIZE=8192KB , FILEGROWTH=65536KB) TO FILEGROUP FG2
GO

