CREATE DATABASE dbtech_olap;

/* Fact table */
CREATE TABLE fact_call_summary
(
	CALL_ID INT PRIMARY KEY FOREIGN KEY REFERENCES dim_call_details(CALL_ID),
	USER_ID INT FOREIGN KEY REFERENCES dim_user_details(USER_ID),
	ACCOUNT_ID INT FOREIGN KEY REFERENCES dim_account_details(ACCOUNT_ID),
	PHONE_NUM_ID INT FOREIGN KEY REFERENCES dim_phone_num_details(PHONE_NUM_ID),
	ORIGIN_TOWER_ID INT FOREIGN KEY REFERENCES dim_tower_details(TOWER_ID),
	DESTINATION_TOWER_ID INT FOREIGN KEY REFERENCES dim_tower_details(TOWER_ID),
)

/* Dimension tables */

/* Call details */
CREATE TABLE dim_call_details
(
	CALL_ID INT PRIMARY KEY,
	CALL_SUCCESSFUL BIT NOT NULL,
	START_TIME DATETIME,
	END_TIME DATETIME
)

/* User details */
CREATE TABLE dim_user_details
(
	USER_ID INT PRIMARY KEY,
	USER_NAME VARCHAR(200) NOT NULL,
	ADDRESS VARCHAR(500) NOT NULL,
)

/* Account details */
CREATE TABLE dim_account_details
(
	ACCOUNT_ID INT PRIMARY KEY,
	CATEGORY VARCHAR(10) NOT NULL CHECK(CATEGORY IN ('personal', 'corporate')),
	OUTGOING_RATE FLOAT,
	INCOMING_RATE FLOAT,
	OUTGOING_LIMIT INT,
	INCOMING_LIMIT INT,
	START_DATE DATETIME NOT NULL
)

/* Phone number details */
CREATE TABLE dim_phone_num_details
(
	PHONE_NUM_ID INT PRIMARY KEY,
	PHONE_NUMBER INT NOT NULL,
	EXTENSION INT NOT NULL,
	IN_USE BIT NOT NULL
)

/* Phone tower details */
CREATE TABLE dim_tower_details
(
	TOWER_ID INT PRIMARY KEY,
	AREA VARCHAR(100) NOT NULL,
	CITY VARCHAR(100) NOT NULL,
	STATE VARCHAR(100) NOT NULL,
	COUNTRY VARCHAR(100) NOT NULL,
)
