SELECT DISTINCT (JOB_LOCATION)
FROM EMPLOYEE, JOB_DETAILS
WHERE EMPLOYEE_AGE < 30

SELECT DISTINCT QUESTION.QUESTION_DIFFICULTY, COUNT(*) AS NUM_QUESTIONS
FROM (((INTERVIEWER JOIN INTERVIEW ON INTERVIEWER.INTERVIEWER_ID=INTERVIEW.INTERVIEWER_ID) JOIN MAP ON INTERVIEW.INTERVIEW_ID=MAP.INTERVIEW_ID) FULL OUTER JOIN QUESTION ON MAP.QUESTION_ID=QUESTION.QUESTION_ID)
WHERE INTERVIEWER.INTERVIEWER_ID=(10)
GROUP BY QUESTION.QUESTION_DIFFICULTY;

SELECT DISTINCT QUESTION.QUESTION_DIFFICULTY, COUNT(*) AS NUM_QUESTIONS
FROM (((INTERVIEW JOIN MAP ON INTERVIEW.INTERVIEW_ID=MAP.INTERVIEW_ID) JOIN INTERVIEWER ON INTERVIEWER.INTERVIEWER_ID=INTERVIEW.INTERVIEWER_ID) FULL OUTER JOIN QUESTION ON MAP.QUESTION_ID=QUESTION.QUESTION_ID)
WHERE INTERVIEWER.INTERVIEWER_ID=(10)
GROUP BY QUESTION.QUESTION_DIFFICULTY;

SELECT DISTINCT QUESTION.QUESTION_DIFFICULTY, COUNT(*) AS NUM_QUESTIONS
FROM (INTERVIEWER JOIN INTERVIEW ON INTERVIEWER.INTERVIEWER_ID=INTERVIEW.INTERVIEWER_ID) JOIN (MAP FULL OUTER JOIN QUESTION ON MAP.QUESTION_ID=QUESTION.QUESTION_ID) ON INTERVIEW.INTERVIEW_ID=MAP.INTERVIEW_ID 
WHERE INTERVIEWER.INTERVIEWER_ID=(10)
GROUP BY QUESTION.QUESTION_DIFFICULTY;


SELECT * FROM EMPLOYEE, JOB_DETAILS WHERE EMPLOYEE.EMPLOYEE_ID NOT IN (SELECT INTERVIEWER.EMPLOYEE_ID FROM INTERVIEWER)
SELECT * FROM EMPLOYEE JOIN JOB_DETAILS ON EMPLOYEE.EMPLOYEE_POSITION=JOB_DETAILS.JOB_TITLE WHERE EMPLOYEE.EMPLOYEE_ID NOT IN (SELECT INTERVIEWER.EMPLOYEE_ID FROM INTERVIEWER)
