CREATE TABLE CANDIDATE
(
  CANDIDATE_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  CANDIDATE_STATUS VARCHAR(100),
  CANDIDATE_EXPERIENCE VARCHAR(100),
  CANDIDATE_NAME VARCHAR(100) NOT NULL,
  CANDIDATE_AGE INT NOT NULL,
  CANDIDATE_EDUCATION VARCHAR(8000),
  CANDIDATE_ROLE INT FOREIGN KEY REFERENCES JOB_DETAILS(JOB_ID) ON DELETE SET NULL
)
