CREATE TABLE JOB_DETAILS
(
  JOB_ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  JOB_LOCATION VARCHAR(100) NOT NULL,
  JOB_TITLE VARCHAR(100) NOT NULL,
  FILLED bit NOT NULL default 'FALSE'
)

CREATE TABLE JOB_ROLE
(
  JOB_TITLE VARCHAR(100) PRIMARY KEY,
  JOB_DESCRIPTION VARCHAR(8000)
)